### ISSUE TITLE
iframe で表示した際、高解像度ディスプレイでぼやけて表示される

### ISSUE THREAD

**Issue by kem198** [kenkenpa198/modane-live2d-widget#1]
README.md に記載しているコードで iframe 要素として表示すると、スマートフォンなどデバイスピクセル比が 2 の端末でぼけて表示されてしまう。

```html
<!-- Example -->
<iframe id="iframe-modane" src="https://kenkenpa198.github.io/modane-live2d-widget/CubismSdkForWeb-4-r.7/Samples/TypeScript/Demo/index.html" frameborder="0"></iframe>
```

iframe で書き出された画素数が単に足りてないぽい。

個人サイトでは下記のようにすることで対策している。

https://github.com/kenkenpa198/kems-clew.net/blob/main/docs/index.html

```html
    <!-- modane-live2d-widget -->
    <div class="modane-wrapper">
        <div class="modane-container">
            <iframe class="modane-iframe" loading="lazy" src="https://kenkenpa198.github.io/modane-live2d-widget/CubismSdkForWeb-4-r.7/Samples/TypeScript/Demo/index.html" frameborder="0"></iframe>
        </div>
    </div>
```

https://github.com/kenkenpa198/kems-clew.net/blob/main/docs/css/style.css

```css
/* ==================================================
 * modane-live2d-widget
 * ================================================== */

/* 単純に iframe 要素のみを表示すると、スマートフォンなどデバイスピクセル比が 2 の端末でぼけて表示されてしまう。
 * このため ★ の処理で対策している。
 *
 * 1. 子要素 iframe を 2 倍のサイズで書き出した後に 1/2 サイズへ縮小して表示する。
 * 2. このままだと領域が 2 倍のままなので親要素 wrapper の overflow: hidden でクリッピングする。
 */

/* 親要素 wrapper */
.modane-wrapper {
    position: fixed;
    right: 50px;
    bottom: 0;
    display: flex;           /* ★ 子要素の中央寄せ */
    justify-content: center; /* ★ 子要素の中央寄せ */
    align-items: center;     /* ★ 子要素の中央寄せ */
    width: 300px;            /* ★ 最終的に表示する大きさ */
    height: 600px;           /* ★ 最終的に表示する大きさ */
    overflow: hidden;        /* ★ 子要素の元サイズが 1200px なのでクリッピングする */
    z-index: 1;
    /* border: 1px solid red; */
}

/* 中間要素 container */
/* wrapper と iframe のみでは iframe の transform が wrapper のサイズを元に縮小してしまう。
 * 結果、ビューポートが狭い時に腕が見切れてしまう場合があるので中間の親要素を設定している。 */
.modane-container {
    /* border: 1px solid blue; */
}

/* 子要素 iframe */
.modane-iframe {
    width: 1200px;         /* ★ 2 倍のサイズで書き出す */
    height: 1200px;        /* ★ 2 倍のサイズで書き出す */
    transform: scale(0.5); /* ★ width, height を 2 倍のサイズで書き出した後に 1/2 サイズへ縮小する */
    /* border: 1px solid green; */

}

/* タブレット・SP 向けのレイアウト */
@media (max-width: 960px) {
    .modane-wrapper {
        position: static;
        margin: 72px auto 0;
        width: auto;
    }
}
```

実際の表示はこちら。

https://kems-clew.net/

かなり冗長なのでなんとかしたい。
